OnlineShoppingMVC/Controllers/DisplayListController.cs
using OnlineShoppingMVC_DAL;
using OnlineShoppingMVC_Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingMVC.Controllers
{
    public class DisplayListController : Controller
    {
        ProductRepostary getProduct;

        public DisplayListController()
        {
            getProduct = new ProductRepostary();
        }

        // GET: DisplayList
        public ActionResult Index()
        {
            IEnumerable<ProductDetails> product = getProduct.ReturnProductDetails();
            return View(product);
        }
        public ActionResult TempDataProduct()
        {
            IEnumerable<ProductDetails> product = getProduct.ReturnProductDetails();
            TempData["Product"] = product;
            return RedirectToAction("TempDataProductRedirect");
        }
        public ActionResult TempDataProductRedirect()
        {
            return View();

        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ActionName("Add")]
        public ActionResult AddProduct(FormCollection Form)
        {
            int id = Convert.ToInt32(Request.Form["productId"]);
            string name = Request.Form["productName"];
            double price = Convert.ToDouble(Request.Form["productPrice"]);
            ProductDetails ProductList = new ProductDetails(id, name, price);
            TryUpdateModel(ProductList);
            getProduct.AddProduct(ProductList);
            TempData["Message"] = "Product added Successfully";
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            ProductDetails product = getProduct.GetProduct(id);
            return View(product);
        }
        public ActionResult Delete(int id)
        {
            getProduct.DeleteProduct(id);
            TempData["Message"] = "Package deleted";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Update()
        {
            ProductDetails ProductList = new ProductDetails();
            UpdateModel(ProductList);
            getProduct.UpdatePackage(ProductList);
            TempData["Message"] = "Package updated";
            return RedirectToAction("Index");
        }
    }
}

OnlineShoppingMVC/Views/DisplayList/Add.cshtml
@model OnlineShoppingMVC_Entity.ProductDetails

@{
    ViewBag.Title = "Add";
}

<h2>Add Product</h2>

@using (Html.BeginForm("Add", "DisplayList", FormMethod.Post))
{
    <table cellpadding="10">
        <tr>
            <td>
                @Html.Label("ProductId")
            </td>
            <td>
                @Html.TextBox("productId")
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(Model => Model.productName)</td>
            <td>@Html.TextBox("productName")
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(Model => Model.productPrice)</td>
            <td>@Html.TextBox("productPrice")
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Back", "Index")
            </td>
            <td>
                <input type="submit" id="Add" />
            </td>
        </tr>
    </table>
}

OnlineShoppingMVC/Views/DisplayList/Edit.cshtml
@model OnlineShoppingMVC_Entity.ProductDetails

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Product</h2>

@using (Html.BeginForm("Update", "DisplayList", FormMethod.Post))
{
    @Html.HiddenFor(Model => Model.productId)
    <table cellpadding="10">
        <tr>
            <td>
                @Html.Label("ProductName")
            </td>
            <td>
                @Html.EditorFor(Model => Model.productName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("ProductPrice")
            </td>
            <td>
                @Html.EditorFor(Model => Model.productPrice)
            </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Cancel", "Index")
            </td>
            <td>
                <input type="submit" value="Update" />
            </td>
        </tr>
    </table>
}

OnlineShoppingMVC/Views/DisplayList/Index.cshtml
@model IEnumerable<OnlineShoppingMVC_Entity.ProductDetails>

@{
    ViewBag.Title = "Index";
}

<h2>Welcome</h2>

@Html.ActionLink("Add New Product", "Add")<br />

@if (TempData["Message"] != null)
{
    @Html.Label((string)TempData["Message"])
}
<h2>Product</h2>
<table border="1">
    <tr>
        <td>Product Name</td>
        <td>Product Price</td>
        <td>Choice</td>
    </tr>
    @foreach (OnlineShoppingMVC_Entity.ProductDetails item in @Model)
    {
        <tr>
            <td>
                @item.productName
            </td>
            <td>
                @item.productPrice
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.productId })
                @Html.ActionLink("Delete", "Delete", new { id = item.productId })
            </td>
        </tr>
    }
</table>

OnlineShoppingMVC/Views/DisplayList/TempDataProduct.cshtml
@{
    ViewBag.Title = "TempDataProduct";
}

<h2>TempData Product</h2>

<table border="1">
    <tr>
        <td>Product Id</td>
        <td>Product Name</td>
        <td>Product Price</td>
    </tr>

    @foreach (OnlineShoppingMVC_Entity.ProductDetails item in (List<OnlineShoppingMVC_Entity.ProductDetails>)TempData["Product"])
    {
        <tr>
            <td>@item.productId</td>
            <td>@item.productName</td>
            <td>@item.productPrice</td>
        </tr>
    }
</table>

OnlineShoppingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>